### ISSUE TITLE
Add support for Laravel Precognition

### ISSUE THREAD

**Issue by vivgui** [fenilli/formkit-addon-inertia#15]
- https://laravel.com/docs/10.x/precognition

Laravel precognition lets you use your server side validation rules on the frontend. The thing is, you cannot have both laravel precog and formkit validation rules, they tend to conflict. 

An improvement would be to add a special syntax like `validation="prec:required"` where the plugin will know to disable the formkit validation when needed.

**Comment by fenilli** [comment]
With the new [@formkit/inertia](https://github.com/formkit/inertia) this will be tracked there, the only reason it was not implemented already in there, is because Laravel Precognition gives console warnings for every call, and that was ugly so I'm delaying until I think of anything that could be implemented for it, as per [#52](https://github.com/laravel/precognition/issues/52).
